name: Build, Push, and Sign Docker Image with Cosign

on:
  push:
    branches:
      - master

jobs:
  build-and-sign:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/my-app:latest .

      - name: Push Docker Image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository }}/my-app:latest

      - name: Get Image Digest
        id: digest
        run: |
          IMAGE_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' ghcr.io/${{ github.repository }}/my-app:latest)
          echo "IMAGE_DIGEST=${IMAGE_DIGEST}" >> $GITHUB_ENV

      - name: Install Cosign
        run: |
          curl -LO https://github.com/sigstore/cosign/releases/download/v2.4.1/cosign-linux-amd64
          chmod +x cosign-linux-amd64
          sudo mv cosign-linux-amd64 /usr/local/bin/cosign

      - name: Get Private Key
        run: |
          echo "${{ secrets.COSIGN_KEY }}" > cosign.key 

      - name: Sign Docker Image with Cosign
        env:
          COSIGN_EXPERIMENTAL: "true"
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          cosign sign --key cosign.key --yes ${{ env.IMAGE_DIGEST }}

      - name: Remove Cosign Key File
        run: |
          shred -u cosign.key