name: Build, Push, and Keyless Sign Docker Image with Cosign

on:
  push:
    branches:
      - master

jobs:
  build-and-sign:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for OIDC authentication with Sigstore
      contents: read

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/my-app:latest .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USER }}/my-app:latest

      - name: Install Cosign
        run: |
          curl -LO https://github.com/sigstore/cosign/releases/download/v2.4.1/cosign-linux-amd64
          chmod +x cosign-linux-amd64
          sudo mv cosign-linux-amd64 /usr/local/bin/cosign

      - name: Keyless Sign Docker Image with Cosign
        env:
          COSIGN_EXPERIMENTAL: "true"  # Enables keyless signing
        run: |
          cosign sign --yes docker.io/${{ secrets.DOCKER_USER }}/my-app:latest